#version 450
#extension GL_EXT_nonuniform_qualifier : require

#include "Common.glsl"

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform samplerCube skybox;
layout (set = 0, binding = 1, rgba32f) writeonly uniform image2D images[];


#define PI 3.141592653589
#define IRRADIANCE_MAP_SIZE 32.0
void main() {

    uvec3 gid = gl_GlobalInvocationID;
    ivec2 texCoord = ivec2(gid.xy);
    int faceIndex = int(gid.z);
    vec2 uv = (vec2(gid.xy) / vec2(IRRADIANCE_MAP_SIZE, IRRADIANCE_MAP_SIZE)) * 2.0 - 1.0;

    vec3 dir = vec3(0.0);
    switch (faceIndex) {
        case 0: dir = normalize(vec3( 1.0, -uv.y, -uv.x)); break;
        case 1: dir = normalize(vec3(-1.0, -uv.y,  uv.x)); break;
        case 2: dir = normalize(vec3( uv.x,  1.0,  uv.y)); break;
        case 3: dir = normalize(vec3( uv.x, -1.0, -uv.y)); break;
        case 4: dir = normalize(vec3( uv.x, -uv.y,  1.0)); break;
        case 5: dir = normalize(vec3(-uv.x, -uv.y, -1.0)); break;
    }

    vec3 N = normalize(dir);
    vec3 irradiance = vec3(0.0);
    vec3 up = abs(N.y) > 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, N));
    up = normalize(cross(N, right));

    float sampleDelta = 0.025;
    float nrSamples = 0.0;
    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
    {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta)
        {
            vec3 tangentSample = vec3(sin(theta) * cos(phi),  sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * N;
            // Some HDR images sometimes have a single or few pixels which are significantly larger
            // in brightness than the rest which results in a banding/dotting effect in the prefiltered map.
            // To avoid this we can clamp the brightness when sampling the cubemap but I am unsure if this is
            // something we should be doing or just use better HDR cubemaps.
            irradiance += clamp(texture(skybox, sampleVec).rgb, 0.0, 100.0) * cos(theta) * sin(theta);
            nrSamples++;
        }
    }

    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    vec4 color = vec4(irradiance, 1.0);
    //vec4 color = vec4(texture(skybox, dir).rgb, 1.0);
    imageStore(images[faceIndex], ivec2(texCoord.xy), color);
}