#version 450
#extension GL_EXT_nonuniform_qualifier : require

#include "Common.glsl"

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform samplerCube skybox;
layout (set = 0, binding = 1, rgba32f) writeonly uniform image2DArray images[];

layout(push_constant) uniform Push
{
    float roughness;
    uint mipLevel;
}pc;

#define PI 3.141592653589

float RadicalInverse_VdC(uint bits)
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}

vec2 Hammersley(uint i, uint N)
{
    return vec2(float(i)/float(N), RadicalInverse_VdC(i));
}

vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float roughness)
{
    float a = roughness*roughness;

    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);

    vec3 H;
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;

    vec3 up        = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent   = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);

    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;
    return normalize(sampleVec);
}

void main() {

    uvec3 gid = gl_GlobalInvocationID;
    ivec2 texCoord = ivec2(gid.xy);
    int faceIndex = int(gid.z);

    //vec2 uv = (vec2(texCoord) / 2048.0) * 2.0 - 1.0;
    const float baseResolution = 128.0;
    float mipResolution = baseResolution / float(1 << pc.mipLevel);
    vec2 uv = (vec2(texCoord) / mipResolution) * 2.0 - 1.0;


    vec3 dir = vec3(0.0);
    switch (faceIndex) {
        case 0: dir = normalize(vec3( 1.0, -uv.y, -uv.x)); break;
        case 1: dir = normalize(vec3(-1.0, -uv.y,  uv.x)); break;
        case 2: dir = normalize(vec3( uv.x,  1.0,  uv.y)); break;
        case 3: dir = normalize(vec3( uv.x, -1.0, -uv.y)); break;
        case 4: dir = normalize(vec3( uv.x, -uv.y,  1.0)); break;
        case 5: dir = normalize(vec3(-uv.x, -uv.y, -1.0)); break;
    }

    vec3 N = normalize(dir);
    vec3 R = N;
    vec3 V = R;

    const uint SAMPLE_COUNT = 1024;
    float totalWeight = 0.0;
    vec3 prefilteredColour = vec3(0.0);
    for(uint i = 0; i < SAMPLE_COUNT; ++i)
    {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H = ImportanceSampleGGX(Xi, N, pc.roughness);
        vec3 L = normalize(2.0 * dot(V, H) * H - V);

        float NdotL = max(dot(N, L), 0.0);
        if(NdotL > 0.0)
        {
            prefilteredColour += texture(skybox, L).rgb * NdotL;
            totalWeight += NdotL;
        }
    }

    prefilteredColour /= totalWeight;

    vec4 color = vec4(prefilteredColour, 1.0);
    //vec4 color = vec4(texture(skybox, dir).rgb, 1.0);
    imageStore(images[nonuniformEXT(pc.mipLevel)], ivec3(texCoord, faceIndex), color);
}