name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: seanmiddleditch/gha-setup-ninja@master


      - name: Install X11
        run: sudo apt-get update && sudo apt-get install libx11-dev


      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Platinum -S . -B build
          cmake --build build -j
          cmake --install build --prefix install
      - name: Zip
        run: |
          Compress-Archive -Path install -DestinationPath release_linux.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_linux"
          prerelease: true
          files: |
            release_linux.zip
