name: Build and Release linux

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libx11-dev libxrandr-dev  libxinerama-dev libxcursor-dev xorg-dev -y

      - name: Build
        env:
          TARGET_PLATFORM: linux
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Platinum -S . -B build
          cmake --build build -j
          cmake --install build --prefix install

      - name: Zip
        run: |
          zip -r release_linux.zip install

      - name: Datetime
        id: datetime
        run: echo "NOW=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: "AUTO RELEASE Linux: ${{ env.NOW }}"
          tag_name: "${{ env.NOW }}"
          files: release_linux.zip
