name: Build and Release windows

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Platinum -S . -B build
          cmake --build build -j
          cmake --install build --prefix install
      - name: Zip
        run: |
          Compress-Archive -Path install -DestinationPath release_windows.zip

      - name: Get current datetime
        id: current_datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-windows-${{ steps.current_datetime.outputs.datetime }}"
          prerelease: true
          title: "AUTO RELEASE Windows: ${{ steps.current_datetime.outputs.datetime }}"
          files: |
            release_windows.zip